src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $price = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $images = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $modifiedAt = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    private ?Category $category_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getImages(): ?string
    {
        return $this->images;
    }

    public function setImages(?string $images): self
    {
        $this->images = $images;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getModifiedAt(): ?\DateTimeInterface
    {
        return $this->modifiedAt;
    }

    public function setModifiedAt(\DateTimeInterface $modifiedAt): self
    {
        $this->modifiedAt = $modifiedAt;

        return $this;
    }

    public function getCategoryId(): ?Category
    {
        return $this->category_id;
    }

    public function setCategoryId(?Category $category_id): self
    {
        $this->category_id = $category_id;

        return $this;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Nom du produit',
                'attr' => [
                    'class' => 'form-control mb-3'
                ]
            ])
            ->add('description', TextareaType::class, [
                'label' => 'Description du produit',
                'attr' => [
                    'class' => 'form-control mb-3'
                ]
            ])
            ->add('images', FileType::class, [
                'label' => 'Images du produit',
                'attr' => [
                    'class' => 'form-control mb-3'
                ],
                'required' => true,
                'mapped' => false
            ])
            ->add('price', TextType::class, [
                'label' => 'Prix du produit',
                'attr' => [
                    'class' => 'form-control mb-3'
                ]
            ])
            ->add('category_id', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'name',
                'attr' => [
                    'class' => 'form-control mb-3'
                ],
                'label' => 'Categorie du produit',
                'placeholder' => 'Chosir la categorie',
                'required' => true
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\Product;
use App\Form\ProductType;
use App\Repository\ProductRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/app/product')]
class ProductController extends AbstractController
{
    #[Route('/', name: 'app_product_index', methods: ['GET'])]
    public function index(ProductRepository $productRepository, Request $request): Response
    {
        if (!empty($request->query->get('categ')) && \is_numeric($request->query->get('categ'))) {
            $listProd = $productRepository->findAllByCateg($request->query->get('categ'));
        } elseif (!empty($request->query->get('filter'))) {
            $listProd = $productRepository->findAllByName($request->query->get('filter'));
        } else {
            $listProd = $productRepository->findAllAndCategories();
        }

        return $this->render('product/index.html.twig', [
            'products' => $listProd
        ]);
    }

    #[Route('/new', name: 'app_product_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ProductRepository $productRepository): Response
    {
        $product = new Product();
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $product->setCreatedAt(new DateTime());
            $product->setModifiedAt(new DateTime());
            $file = $form->get('images')->getData();

            if ($file) {
                $fileName = 'images/' . md5(uniqid()) . '.' . $file->guessExtension();

                $file->move(
                    $this->getParameter('images_directory'),
                    $fileName
                );

                $product->setImages($fileName);
            }

            $productRepository->save($product, true);

            return $this->redirectToRoute('app_product_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('product/new.html.twig', [
            'product' => $product,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_product_show', methods: ['GET'])]
    public function show(Product $product): Response
    {
        return $this->render('product/show.html.twig', [
            'product' => $product,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_product_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Product $product, ProductRepository $productRepository): Response
    {
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file = $form->get('images')->getData();

            if ($file) {
                $fileName = 'images/' . md5(uniqid()) . '.' . $file->guessExtension();

                $file->move(
                    $this->getParameter('images_directory'),
                    $fileName
                );

                $product->setImages($fileName);
            }

            $product->setModifiedAt(new DateTime());

            $productRepository->save($product, true);

            return $this->redirectToRoute('app_product_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('product/edit.html.twig', [
            'product' => $product,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_product_delete', methods: ['POST'])]
    public function delete(Request $request, Product $product, ProductRepository $productRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $product->getId(), $request->request->get('_token'))) {
            $productRepository->remove($product, true);
        }

        return $this->redirectToRoute('app_product_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/product/_delete_form.html.twig
<form method="post" action="{{ path('app_product_delete', {'id': product.id}) }}" onsubmit="return confirm('Voulez-vous vraiment supprimer ce produit ?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
	<button class="btn btn-sm btn-danger">Delete</button>
</form>

templates/product/_form.html.twig
<div class="container">
	<div class="vh-100 d-flex justify-content-center" style="margin-top: -20px;">
		<div class="container">
			<div class="row d-flex justify-content-center">
				<div class="col-12 col-md-8 col-lg-6">
					<div class="card bg-white">
						<div class="card-body p-5">
							{{ form_start(form) }}
							{{ form_row(form.name) }}
							{{ form_row(form.description) }}
							{{ form_row(form.images) }}
							{{ form_row(form.price) }}
							{{ form_row(form.category_id) }}
							<div>
								<button class="btn btn-block btn-outline-success w-100">
									{{ button_label|default('Save') }}
								</button>
							</div>
							{{ form_end(form) }}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

templates/product/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification Produit
{% endblock %}

{% block body %}

	<div class="container-fluid p-5 bg-primary text-white text-center">
		<h1>Modification produit</h1>
	</div>

	{{ include('product/_form.html.twig', {'button_label': 'Enregistrer'}) }}

{# <a class="btn btn-sm btn-link" href="{{ path('app_product_index') }}">Retour a la liste</a> #}

	{# {{ include('product/_delete_form.html.twig') }} #}
{% endblock %}

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des produits
{% endblock %}

{% block body %}

	<a class="btn btn-link" href="{{ path('app_product_new') }}">Ajouter nouveau produit</a>
	<br>
	<hr>
	<br>
	<h2>Liste des produits</h2>
	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<th scope="col">#</th>
				<th scope="col">Nom du produit</th>
				<th scope="col">Description du produit</th>
				<th scope="col">Prix</th>
				<th scope="col">Categorie</th>
				<th scope="col">Images</th>
				<th scope="col">Creation</th>
				<th scope="col">Modification</th>
				<th scope="col">Action</th>
			</tr>
		</thead>
		<tbody>
			{% for product in products %}
				<tr>
					<td>{{ loop.index }}</td>
					<td>{{ product.name }}</td>
					<td>{{ product.description }}</td>
					<td>{{ product.price }}</td>
					<td>{{ product.categoryId.name }}</td>
					<td>
						{% if product.images is not empty %}
							<img src="{{ asset(product.images) }}" class="rounded mx-auto d-block" style="max-width: 200px;">
						{% else %}
							<div class="text-center text-italic">
								Aucune image.
							</div>
						{% endif %}
					</td>
					<td>{{ product.createdAt ? product.createdAt|date('Y-m-d H:i:s') : '' }}</td>
					<td>{{ product.modifiedAt ? product.modifiedAt|date('Y-m-d H:i:s') : '' }}</td>
					<td>
						<a class="btn btn-sm btn-outline-success" href="{{ path('app_product_show', {'id': product.id}) }}">
							Afficher
						</a>
						<a class="btn btn-sm btn-primary" href="{{ path('app_product_edit', {'id': product.id}) }}">
							Modifer
						</a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="9" class="text-center">Aucun produit enregistre.</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

templates/product/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Creation nouveau produit
{% endblock %}

{% block body %}

	<div class="container-fluid p-5 bg-primary text-white text-center">
		<h1>Creation nouveau produit</h1>
	</div>

	{{ include('product/_form.html.twig') }}

	{# <a class="btn btn-sm btn-link" href="{{ path('app_product_index') }}">Retour a la liste</a> #}
{% endblock %}

templates/product/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Details du produit
{% endblock %}

{% block body %}
	<br>
	<h1>Details du produit</h1>
	<br>

	<table class="table">
		<tbody>
			<tr>
				<th>Nom du produit</th>
				<td>{{ product.name }}</td>
			</tr>
			<tr>
				<th>Description du produit</th>
				<td>{{ product.description }}</td>
			</tr>
			<tr>
				<th>Prix du produit</th>
				<td>{{ product.price }}</td>
			</tr>
			<tr>
				<th>Images</th>
				<td>
					{% if product.images is not empty %}
						<img src="{{ asset(product.images) }}" class="rounded mx-auto d-block" style="max-width: 200px;">
					{% else %}
						<div class="text-center text-italic">
							Aucune image.
						</div>
					{% endif %}
				</td>
			</tr>
			<tr>
				<th>Creation</th>
				<td>{{ product.createdAt ? product.createdAt|date('Y-m-d H:i:s') : '' }}</td>
			</tr>
			<tr>
				<th>Modification</th>
				<td>{{ product.modifiedAt ? product.modifiedAt|date('Y-m-d H:i:s') : '' }}</td>
			</tr>
		</tbody>
	</table>

	<div class="container text-center d-flex justify-content-center">
		<a class="btn btn-sm btn-link" href="{{ path('app_product_index') }}">Retour a la liste</a>
		&nbsp;&nbsp;&nbsp;
		<a class="btn btn-sm btn-primary" href="{{ path('app_product_edit', {'id': product.id}) }}">Modifier</a>
		&nbsp;&nbsp;&nbsp;
		{{ include('product/_delete_form.html.twig') }}
	</div>
{% endblock %}